### ISSUE TITLE
Holotypes aren't anymore listed

### ISSUE THREAD

**Issue by ChrFerrer** [rdmpage/alec#19]
When in taxa pages the holotypes don't seems to be listed anymore, e.g.:

- [Q120956483](https://alec-demo.herokuapp.com/Q120956483) 
- [Q66006968](https://alec-demo.herokuapp.com/Q66006968) 
The exemples above are well defined as types of taxa, however when I follow the links to the taxa they are not listed as types while other types still are, e.g.  with [a paratype](https://alec-demo.herokuapp.com/Q66016539).
This may comes from [this in Wikidata](https://www.wikidata.org/w/index.php?title=Q1061403&diff=prev&oldid=1823533295), however it should not be because this new subclass is still a subclass of "type specimen" wich is itself subclass of "type".

**Comment by rdmpage** [comment]
@ChrFerrer Sorry this took so long to look at. 

I believe I've fixed this with https://github.com/rdmpage/alec/commit/b2eaaa32e40a1913afdd9f288f617b8c048210bb. The problem was that my SPARQL query only included things that were types (i.e., [Q3707858](https://www.wikidata.org/wiki/Q3707858)), not things that were subclasses of Q3707858. Hence if you were more specific about the type of type, e.g. holotype [Q1061403](https://www.wikidata.org/wiki/Q1061403) my query failed. Nite to self, see https://stackoverflow.com/questions/62822658/wikidata-sparql-get-subclasses-but-also-return-parent-class

Thanks for drawing this to my attention. Always nice to find out that people are actually using this web site.

**Comment by ChrFerrer** [comment]
Thanks, I try to add manually a lot of data regarding taxonomy in Wikidata so I'm happy to see a web site which tends to generate content showing them. I will potentially have a lot of ideas for this website but I don't have enough knowledge to help regarding the programming.

**Comment by rdmpage** [comment]
@ChrFerrer Suggestions always welcome, programming isn't necessary. Feel free to post issues here and I'll see what I can do to address them.
